sprintfix: 修复 status 的问题

diff --git a/script_tools/gsectl/proxy/linux/gsectl b/script_tools/gsectl/proxy/linux/gsectl
--- a/script_tools/gsectl/proxy/linux/gsectl
+++ b/script_tools/gsectl/proxy/linux/gsectl
@@ -735,7 +735,14 @@ restart_by_rclocal () {
 
 
 status_by_rclocal () {
-    status_by_binary
+    for module in $modules
+    do
+        status_by_binary ${module}
+        if [ $? -ne 0 ];then
+            echo "have $? module start failed"
+            exit 1
+        fi
+    done
     return
 }
 
