feature: systemd

diff --git a/script_tools/gsectl/agent/linux/gsectl b/script_tools/gsectl/agent/linux/gsectl
--- a/script_tools/gsectl/agent/linux/gsectl
+++ b/script_tools/gsectl/agent/linux/gsectl
@@ -4,6 +4,7 @@
 # 切换到本脚本(gsectl)所在的目录，并设置WORK_HOME变量为上一级目录
 cd ${BASH_SOURCE%/*} 2>/dev/null
 WORK_HOME=${PWD%/bin}
+# TODO 安装目录不一定是 /usr/local/gsexxx，感觉这里用倒数更符合预期，例如 /usr/local/gse/agent/bin，取倒 3
 INSTALL_ENV=`echo $WORK_HOME |awk -F/ '{print $4}'`
 
 # 设置agent的max open files
@@ -30,7 +31,7 @@ start_by_binary () {
         info=( $(_status) )
         rt=$?
     	case $rt in
-            0) status="pid:${info[0]} etime:${info[1]} Already RUNNING" ;;
+            0) status="process:gse_agent pid:${info[0]} etime:${info[1]} Already RUNNING" ;;
             1) status="ERROR STATUS" ;;
             2) status="EXIT" ;;
             3) status="Reload or Restart failed" ;;
@@ -52,7 +53,7 @@ start_by_binary () {
         if is_use_systemd ;then
             systemctl status ${INSTALL_ENV}_${module}
         else
-            cat /tmp/start_agent_tmp.log
+            tail /tmp/start_${node_type}_tmp.log
         fi
     fi
 }
@@ -110,6 +111,90 @@ status_by_binary () {
     return $rt
 }
 
+red_echo ()     { [ "$HASTTY" != "1" ] && echo "$@" || echo -e "\033[031;1m$@\033[0m"; }
+blue_echo ()    { [ "$HASTTY" != "1" ] && echo "$@" || echo -e "\033[034;1m$@\033[0m"; }
+green_echo ()   { [ "$HASTTY" != "1" ] && echo "$@" || echo -e "\033[032;1m$@\033[0m"; }
+
+log () {
+     # 打印消息, 并记录到日志, 日志文件由 LOG_FILE 变量定义
+     local retval=$?
+     local timestamp=$(date +%Y%m%d-%H%M%S)
+     local level=INFO
+     local func_seq=$(echo ${FUNCNAME[@]} | sed 's/ /-/g')
+     local logfile=${LOG_FILE:=/tmp/${INSTALL_ENV}_watch.log}
+
+     local opt=
+
+     if [ "${1:0:1}" == "-" ]; then
+          opt=$1
+          shift 1
+     else
+          opt=""
+     fi
+
+     echo -e $opt "[$(blue_echo ${EXTERNAL_IP:-$LAN_IP})]$timestamp|$BASH_LINENO\t$@"
+     echo "[$(blue_echo ${EXTERNAL_IP}-$LAN_IP)]$timestamp $level|$BASH_LINENO|${func_seq} $@" >>$logfile
+
+     return $retval
+}
+
+watch_by_binary () {
+    # TODO 获取服务状态，异常时自动重启服务
+    local module="agent"
+
+    # 设置记录上次脚本运行的文件
+    LAST_RUN_FILE=/var/run/already_run_times_$module
+
+    # 设置告警阈值
+    THRESHOLD=5
+
+    # 如果文件存在，则读取文件中记录的次数
+    if [ -f $LAST_RUN_FILE ]; then
+        run_count=$(cat $LAST_RUN_FILE)
+    else
+        run_count=0
+    fi
+
+    # 检查上一次脚本是否存在
+    if [ -f /var/run/gsectl_check_status.pid ]; then
+        pid=`cat /var/run/gsectl_check_status.pid`
+        if [ -d "/proc/$pid" ]; then
+            # 如果超过阈值，则发出告警
+            if [ $run_count -gt $THRESHOLD ]; then
+                log "`date +'%F %T.%N'` 脚本: $0 检测状态 运行卡住超过$run_count个周期了,不再检测该模块状态: $module"
+            fi
+
+            run_count=$((run_count + 1))
+            echo $run_count > $LAST_RUN_FILE
+            if [ $run_count -gt 5 ];then
+                log "`date +'%F %T.%N'` 上一次脚本: $0 正在运行"
+                return 1
+            fi
+        else
+            echo 0 > $LAST_RUN_FILE
+            log "`date +'%F %T.%N'` 上一次脚本: $0 已结束，开始新的检测"
+        fi
+    fi
+
+    # 记录当前脚本的 PID
+    echo $$ > /var/run/gsectl_check_status.pid
+
+    # 检测gse_agent是否正常存在的逻辑
+    if [ -z "$module" ]; then
+        echo "watch: get module: $module failed"
+        log "watch: get module: $module failed"
+    else
+        if ! _status $module; then
+            stop_by_binary
+            start_by_binary
+        else
+            echo 0 > $LAST_RUN_FILE
+            log "`date +'%F %T.%N'` 上一次脚本: $0 检测状态已恢复,重置计数"
+        fi
+    fi
+    return
+}
+
 start_by_systemd () {
     # TODO 通过 systemd 启动进程
     if is_systemd_supported ;then
@@ -119,6 +204,7 @@ start_by_systemd () {
 
     if is_use_systemd ;then
         systemctl start ${INSTALL_ENV}_${module}
+        __status;
     else
         start_by_binary
     fi
@@ -128,6 +214,7 @@ stop_by_systemd () {
     # TODO 通过 systemd 停用进程
     if is_use_systemd ;then
         systemctl stop ${INSTALL_ENV}_${module}
+        __status;
     else
         stop_by_binary
     fi
@@ -137,18 +224,10 @@ restart_by_systemd () {
   # TODO 通过 systemd 重启
     if is_use_systemd ;then
         systemctl restart ${INSTALL_ENV}_${module}
+        __status;
     else
-        restart_by_binary
-    fi
-}
-
-
-status_by_systemd () {
-    # TODO 获取服务状态
-    if is_use_systemd ;then
-        systemctl status ${INSTALL_ENV}_${module}
-    else
-        status_by_binary
+        stop_by_binary
+        start_by_systemd
     fi
 }
 
@@ -156,8 +235,18 @@ reload_by_systemd () {
     # TODO reload 重载进程
     if is_use_systemd ;then
         systemctl reload ${INSTALL_ENV}_${module}
+        __status;
     else
         reload_by_binary
+    fi
+}
+
+status_by_systemd () {
+    # TODO 获取服务状态
+    if is_use_systemd ;then
+        systemctl status ${INSTALL_ENV}_${module}
+    else
+        status_by_binary
     fi
 }
 
@@ -198,86 +287,9 @@ status_by_crontab () {
     return
 }
 
-red_echo ()     { [ "$HASTTY" != "1" ] && echo "$@" || echo -e "\033[031;1m$@\033[0m"; }
-blue_echo ()    { [ "$HASTTY" != "1" ] && echo "$@" || echo -e "\033[034;1m$@\033[0m"; }
-green_echo ()   { [ "$HASTTY" != "1" ] && echo "$@" || echo -e "\033[032;1m$@\033[0m"; }
-
-log () {
-     # 打印消息, 并记录到日志, 日志文件由 LOG_FILE 变量定义
-     local retval=$?
-     local timestamp=$(date +%Y%m%d-%H%M%S)
-     local level=INFO
-     local func_seq=$(echo ${FUNCNAME[@]} | sed 's/ /-/g')
-     local logfile=${LOG_FILE:=/tmp/${INSTALL_ENV}_watch.log}
-
-     local opt=
-
-     if [ "${1:0:1}" == "-" ]; then
-          opt=$1
-          shift 1
-     else
-          opt=""
-     fi
-
-     echo -e $opt "[$(blue_echo ${EXTERNAL_IP:-$LAN_IP})]$timestamp|$BASH_LINENO\t$@"
-     echo "[$(blue_echo ${EXTERNAL_IP}-$LAN_IP)]$timestamp $level|$BASH_LINENO|${func_seq} $@" >>$logfile
-
-     return $retval
-}
-
 watch_by_crontab () {
-    # TODO 获取服务状态，异常时自动重启服务
-    local module="agent"
-
-    # 设置记录上次脚本运行的文件
-    LAST_RUN_FILE=/var/run/already_run_times
-
-    # 设置告警阈值
-    THRESHOLD=30
-
-    # 如果文件存在，则读取文件中记录的次数
-    if [ -f $LAST_RUN_FILE ]; then
-        run_count=$(cat $LAST_RUN_FILE)
-    else
-        run_count=0
-    fi
-
-    # 检查上一次脚本是否存在
-    if [ -f /var/run/gsectl_check_status.pid ]; then
-        pid=`cat /var/run/gsectl_check_status.pid`
-        if [ -d "/proc/$pid" ]; then
-            # 如果超过阈值，则发出告警
-            if [ $run_count -gt $THRESHOLD ]; then
-                log "`date +'%F %T.%N'` 脚本: $0 检测状态 运行卡住超过30个周期了"
-            fi
-
-            log "`date +'%F %T.%N'` 上一次脚本: $0 正在运行"
-            run_count=$((run_count + 1))
-            echo $run_count > $LAST_RUN_FILE
-            exit 1
-        else
-            echo 0 > $LAST_RUN_FILE
-            log "`date +'%F %T.%N'` 上一次脚本: $0 已结束，开始新的检测"
-        fi
-    fi
-
-    # 记录当前脚本的 PID
-    echo $$ > /var/run/gsectl_check_status.pid
-
-    # 检测gse_agent是否正常存在的逻辑
-    if [ -z "$module" -o "$module" == "all" ]; then
-        for module in ${PROGS[@]}; do
-            if ! _status $module; then
-                stop_by_binary
-                start_by_binary
-            fi
-        done
-    else
-        if ! _status $module; then
-            stop_by_binary
-            start_by_binary
-        fi
-    fi
+    # TODO 获取服务状态，返回、输出协议和 status_by_binary 保持一致
+    watch_by_binary
     return
 }
 
@@ -342,6 +354,32 @@ get_os_type () {
     fi
 }
 
+add_startup_to_boot (){
+    local module=agent
+
+    # 添加启动项到 rc.local
+    get_os_type
+    if [ -f $RC_LOCAL_FILE ];then
+        if [ `egrep "local/${INSTALL_ENV}/${node_type}" $RC_LOCAL_FILE |egrep ${module} |wc -l` -eq 0 ];then
+            echo "[ -f /usr/local/${INSTALL_ENV}/${node_type}/bin/gsectl ] && /usr/local/${INSTALL_ENV}/${node_type}/bin/gsectl start ${module} 1>>/var/log/${INSTALL_ENV}_${node_type}.log 2>&1" >> $RC_LOCAL_FILE
+        fi
+    else
+        if [ -f /etc/rc.d/rc.local ];then
+            if [ `egrep "local/${INSTALL_ENV}/${node_type}" /etc/rc.d/rc.local |egrep ${module} |wc -l` -eq 0 ];then
+                echo "[ -f /usr/local/${INSTALL_ENV}/${node_type}/bin/gsectl ] && /usr/local/${INSTALL_ENV}/${node_type}/bin/gsectl start ${module} 1>>/var/log/${INSTALL_ENV}_${node_type}.log 2>&1" >> $RC_LOCAL_FILE
+            fi
+        elif [ -f /etc/init.d/rc.local ];then
+            if [ `egrep "local/${INSTALL_ENV}/${node_type}" /etc/init.d/rc.local |egrep ${module} |wc -l` -eq 0 ];then
+                echo "[ -f /usr/local/${INSTALL_ENV}/${node_type}/bin/gsectl ] && /usr/local/${INSTALL_ENV}/${node_type}/bin/gsectl start ${module} 1>>/var/log/${INSTALL_ENV}_${node_type}.log 2>&1" >> $RC_LOCAL_FILE
+            fi
+        elif [ -f /etc/init.d/boot.local ];then
+            if [ `egrep "local/${INSTALL_ENV}/${node_type}" /etc/init.d/boot.local |egrep ${module} |wc -l` -eq 0 ];then
+                echo "[ -f /usr/local/${INSTALL_ENV}/${node_type}/bin/gsectl ] && /usr/local/${INSTALL_ENV}/${node_type}/bin/gsectl start ${module} 1>>/var/log/${INSTALL_ENV}_${node_type}.log 2>&1" >> $RC_LOCAL_FILE
+            fi
+        fi
+    fi
+}
+
 add_config_to_systemd () {
 
     local module="agent"
@@ -352,11 +390,14 @@ Wants=network-online.target
 After=network-online.target
 
 [Service]
-WorkingDirectory=/usr/local/${INSTALL_ENV}/agent/bin
-ExecStart=/usr/local/${INSTALL_ENV}/agent/bin/gse_agent -f /usr/local/${INSTALL_ENV}/agent/etc/gse_agent.conf
-ExecReload=/usr/local/${INSTALL_ENV}/agent/bin/gse_agent --reload
-ExecStop=/usr/local/${INSTALL_ENV}/agent/bin/gse_agent --quit
+LimitNOFILE=512000
+LimitCORE=infinity
+WorkingDirectory=/usr/local/${INSTALL_ENV}/${node_type}/bin
+ExecStart=/usr/local/${INSTALL_ENV}/${node_type}/bin/gse_agent -f /usr/local/${INSTALL_ENV}/${node_type}/etc/gse_agent.conf
+ExecReload=/usr/local/${INSTALL_ENV}/${node_type}/bin/gse_agent --reload
+ExecStop=/usr/local/${INSTALL_ENV}/${node_type}/bin/gse_agent --quit
 Type=forking
+KillMode=process
 User=root
 Restart=always
 RestartSec=30s
@@ -372,24 +413,34 @@ EOF
             echo "update ${INSTALL_ENV}_${module}.service"
             cp /tmp/${INSTALL_ENV}_${module}.service /usr/lib/systemd/system/${INSTALL_ENV}_${module}.service
             systemctl daemon-reload
+            systemctl enable ${INSTALL_ENV}_${module}.service
         fi
     else
         echo "copy ${INSTALL_ENV}_${module}.service"
         cp /tmp/${INSTALL_ENV}_${module}.service /usr/lib/systemd/system/${INSTALL_ENV}_${module}.service
         systemctl daemon-reload
+        systemctl enable ${INSTALL_ENV}_${module}.service
     fi
 
     # 删除rc.local里的启动项
     get_os_type
     if [ -f $RC_LOCAL_FILE ];then
-        sed -i "/local\/${INSTALL_ENV}/d" $RC_LOCAL_FILE
+        if [ `egrep "local/${INSTALL_ENV}/${node_type}" $RC_LOCAL_FILE |wc -l` -ne 0 ];then
+            sed -i "/local\/${INSTALL_ENV}\/${node_type}/d" $RC_LOCAL_FILE
+        fi
     else
         if [ -f /etc/rc.d/rc.local ];then
-            sed -i "/local\/${INSTALL_ENV}/d" /etc/rc.d/rc.local
+            if [ `egrep "local/${INSTALL_ENV}/${node_type}" /etc/rc.d/rc.local |wc -l` -ne 0 ];then
+                sed -i "/local\/${INSTALL_ENV}\/${node_type}/d" /etc/rc.d/rc.local
+            fi
         elif [ -f /etc/init.d/rc.local ];then
-            sed -i "/local\/${INSTALL_ENV}/d" /etc/init.d/rc.local
+            if [ `egrep "local/${INSTALL_ENV}/${node_type}" /etc/init.d/rc.local |wc -l` -ne 0 ];then
+                sed -i "/local\/${INSTALL_ENV}\/${node_type}/d" /etc/init.d/rc.local
+            fi
         elif [ -f /etc/init.d/boot.local ];then
-            sed -i "/local\/${INSTALL_ENV}/d" /etc/init.d/boot.local
+            if [ `egrep "local/${INSTALL_ENV}/${node_type}" /etc/init.d/boot.local |wc -l` -ne 0 ];then
+                sed -i "/local\/${INSTALL_ENV}\/${node_type}/d" /etc/init.d/boot.local
+            fi
         fi
     fi
 }
@@ -407,7 +458,7 @@ setup_crontab () {
     (
         crontab -l | grep -v "$WORK_HOME/bin/gsectl"
         echo "#$WORK_HOME Agent check, add by NodeMan @ `date +'%F %T'`"
-        echo "* * * * * $WORK_HOME/bin/gsectl watch 1 >>/tmp/watch_gse.log 2>&1"
+        echo "* * * * * $WORK_HOME/bin/gsectl watch agent 1>>/tmp/watch_gse.log 2>&1"
     ) > "$tmpcron"
 
     crontab "$tmpcron" && rm -f "$tmpcron"
@@ -462,18 +513,17 @@ get_process_runtime (){
                 TIME_DIFF=$(($CURRENT_TIME_S - $START_TIME_S))
 
                 if [ $TIME_DIFF -le 20 ]; then
-                    echo "进程 $PID 已经启动了 $TIME_DIFF 秒, check $i times"
+                    echo "进程 gse_agent -> $PID 已经启动了 $TIME_DIFF 秒, check $i times"
             		p_status=0
                     break 2
                 else
-                    echo "进程 $PID 已经启动了 $TIME_DIFF 秒, 还未重启成功, check $i times"
+                    echo "进程 gse_agent -> $PID 已经启动了 $TIME_DIFF 秒, 还未重启成功, check $i times"
             		sleep 1
                 fi
             fi
         done
 
         if [ $i -eq 20 ];then
-            echo "gse_agent $action failed"
             return $p_status
         fi
     done
@@ -481,26 +531,53 @@ get_process_runtime (){
 }
 
 __status (){
-    if [ "$action" == "start" -o "$action" == "restart" -o "$action" == "reload" ];then
-        get_process_runtime
-        if [ $? -ne 0 ];then
-            echo "gse_agent $action failed"
-            return 3
-        fi
-    fi
+    local module="agent"
 
     # 最多等待20s来判断是否真正启动成功
     for i in {0..20}; do
-	    if _status >/dev/null; then
-            # 启动正常，直接退出，返回码0
-            echo "gse agent start successful"
-            return 0
-        elif [ $i -eq 20 ]; then
-            # i等于20，超时退出，返回码1
-            echo "gse agent start failed"
-            return 1
+        if [ "$action" == "stop" ];then
+            if [ $(ps --no-header -C gse_${module} -o '%P|%p|%a' |egrep "${WORK_HOME}" |wc -l) -eq 0 ];then
+                echo gse_${module} $action $action success
+                break
+            elif [ $i -eq 20 ];then
+                echo "gse_${module} $action $action failed"
+                return 1
+            else
+                sleep 1
+            fi
         else
-            sleep 2
+	        if _status >/dev/null; then
+                # 启动正常，直接退出，返回码0
+                echo "gse agent start successful"
+
+                if [ "$action" == "start" -o "$action" == "restart" ];then
+                    get_process_runtime
+                    if [ $? -ne 0 ];then
+                        echo "gse_agent $action failed"
+                        return 3
+                    fi
+                elif [ "$action" == "reload" ];then
+                    for i in {0..5}; do
+                        get_process_runtime
+                        if [ $? -eq 0 ];then
+                            break
+                        elif [ $? -ne 0 ];then
+                            sleep 2
+                        elif [ $i -eq 5 ];then
+                            echo "gse_agent $action failed"
+                            return 3
+                        fi
+                    done
+                fi
+
+                return 0
+            elif [ $i -eq 20 ]; then
+                # i等于20，超时退出，返回码1
+                echo "gse agent start failed"
+                return 1
+            else
+                sleep 2
+            fi
         fi
     done
 }
@@ -564,12 +641,32 @@ _status () {
     return 0
 }
 
+detect_node_type () {
+    case $WORK_HOME in
+        *"$INSTALL_ENV"/proxy*) node_type=proxy ;;
+        *"$INSTALL_ENV"/agent*) node_type=agent ;;
+        *) node_type=unknown ;;
+    esac
+
+    echo $node_type >$WORK_HOME/.gse_node_type
+}
+
 # main
 action="$1"; shift
 module="agent"
 
 auto_type=$(get_auto_type)
 
+if [ -s $WORK_HOME/.gse_node_type ]; then
+    read node_type ignore <$WORK_HOME/.gse_node_type
+else
+    detect_node_type
+fi
+
+if [ "${node_type}" == "unknown" ];then
+    echo "wrong node type: ${node_type}"
+    exit
+fi
 
 # TODO 根据 auto_type 判断指令集用哪套方法
 if [ $auto_type == "systemd" ]; then
@@ -579,7 +676,6 @@ if [ $auto_type == "systemd" ]; then
       restart) restart_by_systemd;;
       status) status_by_systemd ;;
       reload) reload_by_systemd;;
-      watch) watch_by_crontab;;
       -h|*) usage ; exit 255 ;;
   esac
 elif [ $auto_type == "crontab" ]; then
